sudo: true
dist: trusty
language: cpp
os:
 - linux
compiler:
 - gcc
before_install:
 - chmod +x ./configure
install:
 - ./configure
script:
 - mkdir build
 - cd build
 - cmake ..
 - make
 - cd ..
after_script:
 - bin/FMACM --buildinfo
